api = "0.11"

[buildpack]
  id = "renku/jupyterlab"
  name = "Jupyterlab frontend Buildpack"
  version = "0.2.0"

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"
