version: 2
updates:
  - package-ecosystem: "conda"
    directories:
      - "buildpacks/jupyterlab/bin"
    schedule:
      interval: "weekly"
    enable-beta-ecosystems: true
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
