api = "0.11"

[buildpack]
  id = "renku/rstudio"
  name = "RStudio frontend Buildpack"
  version = "0.2.3-rc1-test"

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"
