api = "0.11"

[buildpack]
  id = "renku/conda-nodefaults"
  name = "Conda nodefaults buildpack"
  version = "0.2.2"

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"
