# Buildpack API version
api = "0.11"

# Buildpack ID and metadata
[buildpack]
  id = "renku/test-ld-library-path"
  version = "0.2.2"
  name = "test LD_LIBRARY_PATH"

# Targets the buildpack will work with
[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"
