# Buildpack API version
api = "0.11"

# Buildpack ID and metadata
[buildpack]
id = "renku/kernel-installer"
version = "0.2.0"
name = "jupyter kernel installer"

# Targets the buildpack will work with
[[targets]]
os = "linux"

# Stacks (deprecated) the buildpack will work with
[[stacks]]
id = "*"
