# Buildpack API version
api = "0.11"

# Buildpack ID and metadata
[buildpack]
  id = "renku/kernel-installer"
  version = "0.2.3-rc1"
  name = "jupyter kernel installer"

# Targets the buildpack will work with
[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"
