# Buildpack API version
api = "0.11"

# Buildpack ID and metadata
[buildpack]
id = "renku/renku-variables"
version = "0.2.0"
name = "Renku Environment Variables"

# Targets the buildpack will work with
[[targets]]
os = "linux"

# Stacks (deprecated) the buildpack will work with
[[stacks]]
id = "*"
