# Buildpack API version
api = "0.11"

# Buildpack ID and metadata
[buildpack]
id = "renku/python-dependency-manager"
version = "0.2.0"
name = "python dependency manager buildpack"
description = "A simple buildpack that requires the dependency manager for python"

# Targets the buildpack will work with
[[targets]]
os = "linux"

# Stacks (deprecated) the buildpack will work with
[[stacks]]
id = "*"
