api = "0.11"

[buildpack]
  id = "renku/vscodium"
  name = "VSCodium frontend Buildpack"
  version = "0.2.3-rc1"

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"
