# Buildpack API version
api = "0.11"

# Buildpack ID and metadata
[buildpack]
id = "renku/homebrew"
version = "0.3.1"
name = "homebrew buildpack"
description = "A buildpack that installs homebrew packages from a Brewfile."

# Targets the buildpack will work with
[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"
