name: Build all

on:
  push:

env:
  CONTAINER_REGISTRY: ghcr.io

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  create-cuda-run-images:
    runs-on: ${{ matrix.PLATFORM == 'linux/arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      fail-fast: true
      matrix:
        PLATFORM:
          - linux/amd64
          - linux/arm64
    env:
      CONTAINER_IMAGE_NAME: ${{ github.repository }}/cuda-build-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_IMAGE_NAME }}
          labels: |
            io.buildpacks.base.distro.name=ubuntu
            io.buildpacks.base.distro.version=24.04
          tags: |
            type=sha,prefix=${{ matrix.PLATFORM == 'linux/arm64' && 'arm64' || 'amd64' }}-

      - name: Build and push cuda build-image
        uses: docker/build-push-action@v6
        with:
          context: ./run-image
          file: ./run-image/Dockerfile
          platforms: ${{ matrix.PLATFORM }}
          build-args: base_image=nvcr.io/nvidia/cuda-dl-base:25.10-cuda13.0-devel-ubuntu24.04
          target: build
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Docker meta cache
      #   id: meta_cache
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ env.DOCKER_PREFIX }}/py-${{ matrix.FLAVOR }}-${{ matrix.FRONTEND }}-cache
      #     tags: |
      #       type=raw,value=${{ matrix.PLATFORM == 'linux/arm64' && 'arm64' || 'amd64' }}
      # - name: Setup pack
      #   uses: buildpacks/github-actions/setup-pack@v5.9.3
      # - name: Build image
      #   working-directory: ./global-images
      #   run: |
      #     BUILD_TAG=$(echo '${{ steps.meta.outputs.json }}' | jq -cr '.tags[0]')
      #     echo "BUILD_TAG=${BUILD_TAG}"
      #     CACHE_IMAGE=$(echo '${{ steps.meta_cache.outputs.json }}' | jq -cr '.tags[0]')
      #     echo "CACHE_IMAGE=${CACHE_IMAGE}"
      #     RUN_IMAGE=${{ matrix.PLATFORM == 'linux/arm64' && env.RUN_IMAGE_ARM64 || env.RUN_IMAGE_AMD64 }}
      #     echo "RUN_IMAGE=${RUN_IMAGE}"
      #     BUILDER_IMAGE=${{ matrix.PLATFORM == 'linux/arm64' && env.BUILDER_IMAGE_ARM64 || env.BUILDER_IMAGE_AMD64 }}
      #     echo "BUILDER_IMAGE=${BUILDER_IMAGE}"
      #     # publish only on pushes to master or release tags
      #     PUBLISH=0
      #     EXTRA_FLAGS=""
      #     if [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
      #       PUBLISH=1
      #     elif [[ "${GITHUB_REF}" =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      #       PUBLISH=1
      #     fi
      #     [ "${PUBLISH:-}" = "1" ] && EXTRA_FLAGS="--publish --cache-image ${CACHE_IMAGE}"
      #     echo "PUBLISH=${PUBLISH}"
      #     echo "EXTRA_FLAGS=${EXTRA_FLAGS}"
      #     pack build "${BUILD_TAG}" \
      #       -p "${{ matrix.FLAVOR }}" \
      #       --builder "${BUILDER_IMAGE}" \
      #       --run-image "${RUN_IMAGE}" \
      #       --env BP_RENKU_FRONTENDS="${{ matrix.FRONTEND }}" \
      #       --platform "${{ matrix.PLATFORM }}" \
      #       --previous-image "${CACHE_IMAGE}" \
      #       ${EXTRA_FLAGS}
