api = "0.11"
[buildpack]
id = "renku/renv"  # Replace 'myorg' with your organization
version = "0.2.3"
name = "Renv Buildpack"

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"
